# testing timeit()
import timeit
print()
print(timeit.timeit('output = 10-5'))
print()
print(timeit.timeit('output = 10.2-5.6'))
print()
print(timeit.timeit('output = 10+5'))
print()
print(timeit.timeit('output = 10.2+5.6'))
print()
print(timeit.timeit('output = 10*5'))
print()
print(timeit.timeit('output = 10.2*5.6'))
print()
print(timeit.timeit('output = 10/5'))
print()
print(timeit.timeit('output = 10.2/5.6'))